[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]

[project]
dependencies = [
  "torch",
  "numpy",
  "einops",
  "tqdm",
  "plotly",
  "matplotlib",
  "pandas",
  "easy-transformer@git+https://github.com/neelnanda-io/Easy-Transformer",
  "rich",
  "pysvelte@git+https://github.com/neelnanda-io/pysvelte",
  "wandb",
  "transformers",
  "gdown"
]
name = "solu"
version = "0.0.1"
