[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]

[project]
dependencies = [
  "easy-transformer@git+https://github.com/neelnanda-io/Easy-Transformer",
  "einops",
  "gdown",
  "ipywidgets",
  "matplotlib",
  "numpy",
  "pandas",
  "plotly",
  "rich",
  "termcolor",
  "torch",
  "tqdm",
  "transformers",
  "wandb",
  "torchtyping",
  "tqdm"
]
name = "codegen"
version = "0.0.1"
